[package]

name = "markdown"
version = "0.0.1"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "Native Rust library for parsing Markdown and (outputting HTML)"
repository = "https://github.com/johannhof/markdown.rs"
readme = "README.md"
keywords = ["markdown", "md", "html", "parser"]
license = "MIT"

exclude = [
    "test.md"
]

[dependencies]
regex_macros = "0.1.21"
regex = "0.1.41"

[dependencies.text-diff]
git = "https://github.com/johannhof/text-diff.rs.git"
